### ISSUE TITLE
大佬，端口号是多少啊

### ISSUE THREAD

**Issue by the-best-richer** [Dawnnnnnn/Hook_WeChat_FaaS_Xposed#1]
我用lspatch勾选微信后启动到小程序，然后 访问 手机ip地址:80 或者 59999 都访问不了

**Comment by Dawnnnnnn** [comment]
大概是不支持lspatch的吧

**Comment by the-best-richer** [comment]
> 大概是不支持lspatch的吧

大佬，我没用lspatch，用的是lsposed
